### ISSUE TITLE
Options page instructions correction

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#100]
**Current Behavior**: Old instructions on the options page – the number's wrong (two instances)
![image](https://user-images.githubusercontent.com/7329361/38507388-642deeec-3bea-11e8-808e-e9771036691d.png)

**Desired Behavior**: Reflect current behavior.

**Comment by ethanbutler** [comment]
@KimPatch I pushed a change that updates the number to 11 (which is how many total posts show on the page) and that hides the curated UI if it's not enabled.

**Comment by KimPatch** [comment]
@EthanButler – this is what I'm seeing – looks like the change somehow didn't go through:
![image](https://user-images.githubusercontent.com/7329361/38560101-dd5944de-3ca2-11e8-8ded-12854758d2d5.png)

**Comment by ethanbutler** [comment]
@KimPatch – this should be addressed.

**Comment by KimPatch** [comment]
@ethanbutler 
Thanks – there's a new behavior that shouldn't be there – under "Home Options" when I uncheck the "Show Content Role on Homepage" box the "Curated Home Content" field disappears – it shouldn't. (This works correctly under "Blog Options" – the field doesn't disappear)
One very small thing – "11" should be numerical in both instances.

**Comment by KimPatch** [comment]
Looks good!
