### ISSUE TITLE
Blog homepage not updating order correctly

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#111]
- [ ] The blog homepage doesn't reflect changes I've made in Options/Blog Options past item 3
- [x] The Options "Add Entry" button grays out after I've added seven blog entries – I expected 11
- [ ] Only four of the extra entries appear on the blog homepage – all eight should appear

(These could be related to switching to the template to make sure the blog permalink couldn't be overwritten – apologies if I caught you in the middle of fixing that, but I wanted to make sure you knew about these.)

**Comment by ethanbutler** [comment]
@KimPatch I pushed a fix that addresses the "Add Entries" button. The other two items seem to be working correctly – I did notice that one of the interactives you'd included was marked not to show in feeds, so that might explain any confusing behavior.
