### ISSUE TITLE
Blog bucket doesn't show up on the front page of the Production site

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#116]
**Current Behavior**: The production site doesn't have the purple blog box at the bottom of the page

**Desired Behavior**: The production site should have the purple blog box at the bottom of the page just like the staging site.

**Other details:** I see that the eight boxes are gone, so I know the changes have been pushed to production, but the blog bucket is not there at the bottom.

**Comment by ethanbutler** [comment]
Hi @KimPatch – I mentioned this in my email. I hid this on the production site because there's no content at the moment. When content is ready, we can remove the few lines of CSS (in the Custom CSS editor) that hide the bucket currently.

**Comment by KimPatch** [comment]
Got it.
