### ISSUE TITLE
Supporting Content Internal Link Glitch

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#121]
**Current Behavior**:  Internal link added in Supp. Content.vtt tab comes through as external link on the supporting content tab and site._

**Desired Behavior**: Internal link should remain internal link._

**Other details:** Here's a sequence showing this including some odd details – this is consistent behavior.  
I'm using this Interview:
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=105&action=edit
And putting at the top of Supporting Content(.vtt) 
```
00:03.000 --> 00:10.000
LABEL This is the internal link version of title, but it’s optional 
DESCRIPTION This is an optional description
URL http://rlh.demo.sqnts.xyz/interviews/dean-rusk-part-2/
TIMESTAMP #5805
```
I make sure the “update from raw…” checkbox is checked and click Update

Results:
The new Internal link shows up in the Supp. Content tab and on the site as an external link
There’s also a bit of odd behavior – note that the title is automatically applied instead of using the LABEL text. In an internal the title automatically applied when LABEL (the internal version of title) is left blank.

Here's how it looks on the site – it is incorrectly an external link:
![image](https://user-images.githubusercontent.com/7329361/38940845-2c31ce08-42f9-11e8-9b3d-a0b033b6ca04.png)

Here’s what it looks like in the Supp. Content tab – it uses the external link dialog rather than the internal link dialog:
![image](https://user-images.githubusercontent.com/7329361/38940893-56053c24-42f9-11e8-9a2e-8f420a1e2e5b.png)

First update:
The first time I updated  from the Supp. Content tab (with the code still in the .vtt tab), it reverted to the external link dialog, and the code was still in the .vtt tab. 

Second update:
I deleted the item, filled in the internal link dialog again and updated and the Internal link dialog stayed. It is correct on the site.
![image](https://user-images.githubusercontent.com/7329361/38940963-7cf98970-42f9-11e8-9db4-e5b92bb7e3c7.png)

And it comes through on the Supp. Content.vtt tab – it’s correct, but note spacing issues – there’s an extra blank line after the timecode and  description and URL are on the same line

```
00:03.000 --> 00:10.000

LABEL This is the internal link version of title, but it's optional
DESCRIPTION this is the descriptionURL http://rlh.demo.sqnts.xyz/interviews/dean-rusk-part-2/
TIMESTAMP #5805
```

When I remove the item from the Supp. Content tab and update, it’s removed from the site and supplemental content tab, but it still shows up in the Supp. Content.vtt tab

When I make sure the box is checked and update from the Supp. Content.vtt tab it reverts back to a URL, as above, but takes the title from the next entry.
![image](https://user-images.githubusercontent.com/7329361/38941025-a0a60aec-42f9-11e8-8751-35fdc02d115a.png)

Thoughts on what’s happening here?

**Comment by ethanbutler** [comment]
@KimPatch – sorry for taking so long to get to this issue. This is the correct behavior. Because you use `URL` as a label, it gets parsed as an external link. I just changed the label to `INTERNAL_URL` and it behaved as expected.

I think this is just a documentation issue – I'll put together a quick guide on how these are supposed to be formatted.

**Comment by ethanbutler** [comment]
[Documentation here](https://github.com/DukeLivingHistory/RLH-Site-Code/blob/master/docs/editing/EXAMPLE_SUPPORTING_CONTENT_VTT.MD)
