### ISSUE TITLE
Supporting Content Indicator Visibility

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#126]
**Current Behavior**: At middle widths, the supporting content disappears completely behind the medium picture – at wide and narrow widths, the first bit of the supporting content indicator shows behind the medium video_

**Desired Behavior**: _The first bit of supporting content indicator to show behind the video at all widths._

Here's how it looks at a narrow width – the indicator peaks out from behind the  video:

![image](https://user-images.githubusercontent.com/7329361/39094383-7ba803d4-45fc-11e8-8334-c791a00bef3b.png)

Here's the problem width in the middle – tthere's a point where the indicator does not show behind the video:

![image](https://user-images.githubusercontent.com/7329361/39094404-d4b5f774-45fc-11e8-99cf-f2e4a2e63e08.png)

Here's a wider width – the indicator peeks out from behind the video here:

![image](https://user-images.githubusercontent.com/7329361/39094442-40ebb74e-45fd-11e8-8bf2-e6af9090c6ab.png)

There's no problem at even wider or even narrower widths – it's just that point in the middle where it disappears. (This is more of an issue on laptops set to full screen – there's not much room below the picture, which makes it easy to miss the supporting content completely if you can't see it peeking out. The medium video is desirable because you can see the video better, but you don't want to miss the supporting content. It's fine if it's mostly covered – you just need to know there's something there and continue to be able to use it to orient.)

**Comment by KimPatch** [comment]
I see that the fix was to make the video smaller. It looks like there's more elbowroom than needed now and also, the video is considerably smaller. 
A couple of questions:
- Is it viable to move the indicators slightly closer to the text so we can keep the video as large as possible and also the supporting content indicators showing? I think it would be fine to lose as much as 1/4 of the space between the indicators and the text. Let me know if this is viable – if it is, I think this would be the best fix, or part of a fix.
- If this isn't viable, or doesn't do enough, can you size the video so so at the worst point it just peeks out – we don't have to see much of it, just know that it's there. If half the link icon shows, that's enough:
![image](https://user-images.githubusercontent.com/7329361/39641130-1e0c1cda-4f9b-11e8-8e97-f0a52e9d8602.png)
Thanks.

**Comment by ethanbutler** [comment]
@KimPatch I just pushed a change that bumps this up from 33% of the viewport width to 39% – previously it was at 40%.

**Comment by KimPatch** [comment]
@ethanbutler It looks like that almost does it – there's still a size where only the very point sticks out and it's difficult to see. I think if you change the viewport with the 38% it would do it.  Thanks.

**Comment by ethanbutler** [comment]
@KimPatch I made this change and went ahead and pushed to production along with the two other issues that were open. I'll let you close this issue after you've had a chance to review.

**Comment by KimPatch** [comment]
looks good!
