### ISSUE TITLE
Confusing Selection behavior

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#13]
There are two selection behaviors that are confusing users:

1. When I select text, then click elsewhere in the interview (anywhere on text that's not playing), everything below the new place I clicked is then selected. I'm expecting the original selection to just go away and the cursor to be where I clicked without any selection. (This works as expected if I click on text that's playing.) 

2. If I select starting even a little beyond the words left margin the selection jumps to everything below the cursor. It's common for people to overshoot when they want to select all the way to the left margin, and not even realize it so it's confusing when everything is selected. **Question:** Can we either remove this behavior or change the starting point to further into the left margin?

**Comment by ethanbutler** [comment]
@KimPatch The referencing commit resolves #2 – let me know if it also resolves #1. Thanks!

**Comment by KimPatch** [comment]
They both look good – thanks
