### ISSUE TITLE
Interactive pages contents drop-down

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#130]
**Current Behavior**: Interactive pages don't have contents drop-down. 

**Desired Behavior**: Interactive pages should have contents drop-down just like interview pages.

**Other details:** It would be best if there were a checkbox so the content creator could show/hide the table of contents drop-down on Interactive pages.

**Comment by KimPatch** [comment]
Saying this a better way here –  looks good, but needs a small adjustment. It's crowding the title – there needs to be a bit more space between the title and drop-down – maybe double what's there now or whatever makes sense. 
![image](https://user-images.githubusercontent.com/7329361/39636636-d6e705f6-4f8e-11e8-91a8-3d20eb5c710b.png)
(It looks like it's currently the same space as the interview sticky header, but the interview sticky header title is a bit smaller.)

**Comment by ethanbutler** [comment]
@KimPatch – I just pushed a change that bumps this up from 5px to 10px.

**Comment by KimPatch** [comment]
Thanks – looks good!
