### ISSUE TITLE
Search results order

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#133]
**Current Behavior**: It looks like order of the return search results might be order posted, but there's no way to tell and so it looks to the user like it's random.

**Desired Behavior**: Add the change view alphabet/chronological controls that are currently on the Interviews page to the search results page so users can toggle between alphabetical and chronological results returned.

**Comment by KimPatch** [comment]
A quick fix for this would be to change the default view to alphabetical, if it's easier to do that than to add the controls. Ultimately we want to add the alphabet/chronological controls

**Comment by ethanbutler** [comment]
@KimPatch – I pushed a change to order search results by title. I'm going to move the request for controls over to #54, since it's more of a UI concern.

**Comment by KimPatch** [comment]
@ethanbutler 
Default search order looks good – thanks. Makes sense to move the controls to 54 – thanks.
