### ISSUE TITLE
Menu Bugs

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#137]
Staging site: 
- [ ] Click Interviews on the main menu across the top of the page and you still get a blank page

Staging site and production site: 
- [ ] Subitems don't appear in sidebar menus. Appearance/Menus/Our Research Menu
Settings on the staging site (also confirming that I hit the Save Menu button):
![image](https://user-images.githubusercontent.com/7329361/39374438-d707887e-4a18-11e8-95f2-d51e82b96d2b.png)

Despite these settings, the About submenu item doesn't appear on the Our Research sidebar menu:
![image](https://user-images.githubusercontent.com/7329361/39374661-98d6f084-4a19-11e8-8cdf-71826825fd01.png)
I also tested this on the production site – same issue. There was an existing submenu item that disappeared at some point before this week.
Does this have something to do with adding the submenu items on the main menu across the top?

**Comment by KimPatch** [comment]
Footer spacing can get messed up depending on the content in the primary menu. This the case on the staging site in the demo site. These are the sites where we changed the primary menu and added subitems. We haven't yet done that with the production site.

Staging site
![image](https://user-images.githubusercontent.com/7329361/44095771-a0f27516-9fa7-11e8-84a8-85827fa6911e.png)

Demo Site
![image](https://user-images.githubusercontent.com/7329361/44095822-c126b284-9fa7-11e8-9a66-684a0c399c25.png)

Production Site
![image](https://user-images.githubusercontent.com/7329361/44095954-10e848c8-9fa8-11e8-968f-cc62cbc734d4.png)

**Comment by ethanbutler** [comment]
@KimPatch – I fixed this by setting it so that only top-level items show up in the footer.

**Comment by KimPatch** [comment]
great – thanks
