### ISSUE TITLE
Double Click

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#14]
In interview text, selecting brings up the share dialog box, as it should. But double-clicking also brings up the share dialog box, which is confusing if nothing is selected. Can we remove the stray double-click behavior?

**Comment by KimPatch** [comment]
After #13 was mainly fixed, I'm usually getting full words on double-click instead of just a space, which makes this a much smaller problem.

**Comment by ethanbutler** [comment]
Closing this – I'm not sure where the status was left, but the recent changes introduced a check that blocks empty selections from triggering the share dialog.

**Comment by KimPatch** [comment]
Confirming that this is fixed –  Great!
