### ISSUE TITLE
iPhone iPad jump back when text is selected

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#145]
**Current Behavior**: On an iPad and iPhone running Safari when a transcript sentence is touched, it is briefly highlighted blue, as it should be, but then the highlight briefly jumps to the sentence before, then back. This odd jump happens across interviews. It happens at least 20 percent of the time I click a sentence, and for some stretches at a much higher rate. I'm seeing this on my iPhone both with a cell connection and Wi-Fi, and on iPad Pro on Wi-Fi.

**Desired Behavior**: the highlight should stay with the sentence touched rather than jumping.

**Other details:** This doesn't happen on a computer, including on Safari.

**Possibly related question:** Is the site running the current version of Able Player?

**Comment by ethanbutler** [comment]
This is a bug on AblePlayer's end, as I can replicate it on this [demo page](https://ableplayer.github.io/ableplayer/demos/youtube.html). I'm not sure if it's just the YouTube implementation, or across the board. Can you open an issue with them?

**Comment by KimPatch** [comment]
@ethanbutler I started to open an issue with Able Player, but I think the issue is on the Duke end. When I tested the Able Player demo page you pointed to, the bug wasn't present. The highlighting briefly flickers when you click a quote which I think is a feature – it draws your eye. This is different than what is happening on the Duke site. On the Duke site the highlight flickers *and* jumps back to the quote before then jumps forward.

**Comment by ethanbutler** [comment]
Yes, we are running the current version. I'm able to consistently replicate the issue on the page that I linked, and there isn't anything in our code base that would explain the issue. I'm leaving this as wontfix for now.

**Comment by KimPatch** [comment]
Thanks. I checked other devices and I did see the Able Player Demo page jump back, so I can open an issue. On an iPad Pro the Duke site always jumps back but I can't reproduce this with the Able Player Demo site. On a regular iPad and on my phone the Duke site jumps back most of the time and the Able Player Demo site jumps back just occasionally.
