### ISSUE TITLE
Description button

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#146]
**Current Behavior**: The button to toggle video descriptions on and off has disappeared from the video interface._

**Desired Behavior**: The button to toggle video descriptions on and off should appear._

**Comment by ethanbutler** [comment]
This should be resolved!

**Comment by KimPatch** [comment]
@ethanbutler 
I see the button, but I think there's still a connection missing. I'm looking at at Kim TESTING Audio Description and Supporting Content on the staging site (I put it in a testing collection).
I have a couple of test descriptions under the descriptions tab, the descriptions button is there, and it toggles the descriptions field open below the video, but  I don't see the descriptions text in gray in the transcript like they used to be so you could see them in context and search on them. The descriptions also don't show up in the descriptions field when I come to the place in the transcript where they should.

**Comment by ethanbutler** [comment]
The non-appearing description might be an issue with Able Player itself, or it might be an issue with the description file. [This](http://rlh.demo.sqnts.xyz//wp-content//uploads//2018//06//kim_testing_audio_description_and_supporting_content_description.vtt) is what's being loaded as the description. It looks like there's a missing "0" on the first timestamp, and the file is missing the WEBVTT signature at the top, which might create the issue.

I'll have time to look into the transcript issue (which would be on our end) over the weekend. It might also be related to formatting issues.

**Comment by KimPatch** [comment]
I corrected the file – the drop-down box now has descriptions, but they are still missing in the text (and thus doesn't show up in search). It'd be great if you could look into this if you still have time in June maintenance.

**Comment by KimPatch** [comment]
Continuing from above, here's another clue/bug. Go to http://rlh.demo.sqnts.xyz/interviews/kim-testing-2/, 
Click on the transcript, the video jumps to that part of the transcript as it should. 
Click the descriptions button,  you'll see the descriptions in the box (but not the text)  but now when you click on the transcript the video does not jump to that place.  
Refresh the file, descriptions remain in place, and navigation works. 
Click descriptions off and navigation stops responding. 
Refresh and navigation responds.

**Comment by KimPatch** [comment]
@ethanbutler 
Great – the gray text in brackets looks good. One detail, can you take the text out of italic and preface it with this:
Audio Description:

Many thanks.

**Comment by KimPatch** [comment]
@ethanbutler 
Just noticed one more thing – the seek bar indicator doesn't show up for descriptions like it should. Under Options description hits are set to show up as blue dots – I reset to make sure, but the blue dots are not showing up on the seek bar. (I am seeing the hits highlighted yellow in the text, as it should be.)
Testing here:
http://rlh.demo.sqnts.xyz/interviews/kim-testing-2/
![image](https://user-images.githubusercontent.com/7329361/42636428-cd10784c-85b6-11e8-8d00-1ddc2da7956a.png)

**Comment by ethanbutler** [comment]
@KimPatch – these changes are made and pushed to staging and production.

**Comment by KimPatch** [comment]
@ethanbutler 
Thanks – and thanks for pushing them. This works for a basic demo, but there are three details that are off: 
1. It looks like the brackets around the descriptions are now gone – the brackets should remain. 
2. The term Audio Description is not selectable – it should be selectable (just like Interviewee names). Otherwise it gets confusing if it's included in a selection that's shared.
3. Descriptions now appear in the seek bar, which is great, but they show up as red dots. The descriptions color is set for blue:
![image](https://user-images.githubusercontent.com/7329361/42694000-e42f535e-867e-11e8-99b1-88bb1ee6aa40.png)

**Comment by KimPatch** [comment]
@EthanButler Looks great! Descriptions color is correct, Audio Description Is selectable, and the brackets are back. One minor detail – the open bracket should appear before "Audio Description"
So it looks like this:

> [Audio Description: This is a test of the descriptions – I'm expecting this to show up in gray in the transcript when the description icon video control is activated. This makes description searchable. They should also show up in the descriptions box under the video.]

Rather than this:

> Audio Description: [This is a test of the descriptions – I'm expecting this to show up in gray in the transcript when the description icon video control is activated. This makes description searchable. They should also show up in the descriptions box under the video.]

**Comment by KimPatch** [comment]
@ethanbutler – thanks for the fix – looks good on the staging site
