### ISSUE TITLE
Menu sub items don't appear

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#147]
**Current Behavior**: Menu subitems  are specified in appearance/menus but do not appear on the site.

**Desired Behavior**: Menu subitems should appear.

**Other details:** Example on the staging site – Take a look at the Research menu. This is also the case on the Production site with a different Research menu. Related issue: the Interviews menu item on the Staging site comes up blank  – this is not the case on the production site

**Comment by ethanbutler** [comment]
Duplicate of #137
