### ISSUE TITLE
Alphabetical order for collections pages

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#170]
**Current Behavior**: _The order of interviews on the collection pages is not alphabetical._

**Desired Behavior**: _The order of Interviews on the collection pages should be alphabetical._

For example: http://livinghistory.sanford.duke.edu/collections/north-carolina-voting-rights/  Should appear in alphabetical order.

**Comment by ethanbutler** [comment]
@KimPatch I just pushed a fix for this to staging.

**Comment by KimPatch** [comment]
@ethanbutler It looks like these go in alphabetical order according to first name rather than following the sort term order specified in interview options. I checked the Bunker and Rusk sort terms and they are correctly "Bunker" and "Rusk"

![image](https://user-images.githubusercontent.com/7329361/46575006-05c8b480-c97b-11e8-89dc-ffdef9b5e242.png)

**Comment by ethanbutler** [comment]
@KimPatch - good catch, I just pushed a fix.

**Comment by KimPatch** [comment]
@ethanbutler  Looks good – thanks!
