### ISSUE TITLE
Wider view for interactive pages  – same settings as archive

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#173]
**Current Behavior**:  Interactive pages often have three columns – the sidebar, main content, and supporting content. On larger monitors or zoomed out, the main content area gets very narrow compared to the white space around it. Because of the three columns, it would be better to allow the interactive pages to expand.

**Desired Behavior**:  On large monitors or zoomed out, the page margins should change for interactive pages similar to the way the archive page margins change to accommodate six across (#150).

![image](https://user-images.githubusercontent.com/7329361/44609325-38509080-a7c5-11e8-8faa-e013c39f3b28.png)

**Comment by KimPatch** [comment]
@ethanbutler I see that this is been changed, but instead of just being changed on the interactive pages, it's across the site. The margins are now wider than what they were on the Archive page. Can you adjust this so the margin on the left and right stays the same as the Archive page currently works on the production site?

Like this (production site archive page).

![image](https://user-images.githubusercontent.com/7329361/52378756-8d602600-2a36-11e9-9d87-18843d57885a.png)

Rather than of this (staging site archive page).
![image](https://user-images.githubusercontent.com/7329361/52378825-bd0f2e00-2a36-11e9-8d3b-385d6d5a2b34.png)

**Comment by ethanbutler** [comment]
This should be resolved. I pushed a change so that the main content wrapper is 90% of the viewport, up until a maximum of 1800px.

**Comment by KimPatch** [comment]
@ethanbutler 
Great – looks good. There's one remaining detail. The sticky header doesn't adjust and should.

![image](https://user-images.githubusercontent.com/7329361/52565619-56429980-2dd5-11e9-8909-6092e10b166c.png)

**Comment by KimPatch** [comment]
@ethanbutler

**Comment by KimPatch** [comment]
@ethanbutler 
It looks like there's an unintended consequence of making this change site-wide that should be fixed. The right margin has also changed for pages that don't have supporting content (page like the about page and regular blog posts). We need the right margin for pages that don't have supporting content to remain as they were or to have a right margin that's different from pages with supporting content. Otherwise these pages can get too wide on wide monitors. A good example is the About page. Is it possible to adjust the right border on regular pages and regular blog posts without affecting interactive pages, which now look good?

**Comment by ethanbutler** [comment]
This should be resolved!

**Comment by KimPatch** [comment]
@ethanbutler looks good – thanks!
