### ISSUE TITLE
Supporting content "open on default" doesn't adjust

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#174]
**Current Behavior**: When supporting content "open on default" is checked and a viewer opens that interview, the is opened, but subsequent supporting content markers remain out of place – pushed down._

**Desired Behavior**: Subsequent supporting content markers should jump back into place when supporting content is opened by default  just as they do when the viewer clicks on supporting content to open it manually._

**Comment by ethanbutler** [comment]
@KimPatch I've pushed a patch for this to staging.

**Comment by KimPatch** [comment]
@ethanbutler looks good – thanks
