### ISSUE TITLE
Format no media whitelist stopped working

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#187]
@ethanbutler 
adding the Email about the whitelist issue that you fixed earlier this month to make sure the Github project is up-to-date:

Ask from April email thread: 
It looks like the Interactive Pages Format button is unresponsive to the Options/whitelisted items. I suspect this might have been an oversight when you switched over to the new way of doing the Format button (which otherwise is working very well) and it might be trivial to fix. If this is the case it would be great if you could connect it back up.

**Comment by ethanbutler** [comment]
This change has been pushed to production.
