### ISSUE TITLE
Site-wide instructions field for interview content

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#21]

**Comment by ethanbutler** [comment]
Will also contain a note about ctrl/cmd+f.

**Comment by KimPatch** [comment]
Here's the sample for this – we'd want no more spacing than happens when we do these instructions manually. Ideally we want to be able to format the text in the field as well (HTML is fine if that's easiest).
http://livinghistory.sanford.duke.edu/interviews/david-fahrenthold/
