### ISSUE TITLE
Site search bugs

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#35]
The site search (at the top of all pages) seems to be limited to single words that appear in Interview titles and descriptions, the Timeline titles and descriptions, and collection titles.

A couple of bugs:
1. Multiple word searches do not work, e.g. Evan Osnos returns nothing even though these two words appear as a phrase and the single words are found
2. Collection descriptions should be included

**Comment by ethanbutler** [comment]
I expect the proposal in #37 should mitigate the issues you're seeing, but if not I can revisit this issue.

**Comment by KimPatch** [comment]
Multiword searches look good!
