### ISSUE TITLE
Improve site search

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#38]
Site search Searches on title and description and returns a list of interviews that match. It would be an improvement if matches were also highlighted on that return page. What would it take to do this?

**Comment by ethanbutler** [comment]
To clarify, would you want results highlighted on the search results page or on the interview page (after a user has clicked through)? I'd estimate about an hour of effort for the search results page, and about two hours of effort for the interview page.

**Comment by KimPatch** [comment]
Yes, both. And ideally the search results page would have a list of interviews with hits, and then below each listed interview each hit in the interview represented by a line of text with the hit highlighted so you can see the hit in a bit of context and you can see everything at once. Then when you click on a hit, he would go straight to that place in the interview with the hit highlighted (you should also be able to hit the back button to go back to the search page so you can then go to another hit without doing the search again). It would also be useful to have a couple of numbers displayed on the search page – the number of interviews with hits and total hits.

**Comment by KimPatch** [comment]
I think the search return should look something like this:

**14 hits in 5 files**
**Interview <File name> 3 hits**
Line of text with hit highlighted
Line of text with hit highlighted
Line of text with hit highlighted
**Timeline <File name> 2 hits**
Line of text with hit highlighted
Line of text with hit highlighted
**Page <File name> 1 hit**
Line of text with hit highlighted
…

The file name line should be clickable and take the viewer to the top of file (with all the hits In that file highlighted)
Each hit should also be clickable and take the viewer directly to that hit (with all the hits In that file highlighted)
One thing to think about is order –  should all interviews come first, then timelines, than pages aand then by number of hits
The Site search and Collections searches should both be enabled this way
