### ISSUE TITLE
BUG: copy link sometimes failing

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#41]
The copy link often fails when there’s a link in the text I’m trying to copy. I had to copy a whole bunch of excerpts from  this a couple of days ago and saw this behavior many times. Here I’m redoing reproducing a bit of it:

For example, I’m here, and I’m trying to copy the first paragraph that has links – it has two links
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/

I try to copy  the whole paragraph, which has two links, and I get  “undefined” rather than the link and number:
Well, in the days before the elections, there was constant interaction between the experts at CIA, FBI and NSA. We were monitoring and using our collection capabilities to understand what the Russians might have up their sleeve at the 11th hour. 
undefined

I try to copy just a snippet that has one link and the number is missing:
Well, in the days before the elections, there was constant interaction between the experts at CIA, FBI and NSA.
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/

I try to copy just a snippet that has one link a second time, and I get the number this time:
Well, in the days before the elections, there was constant interaction between the experts at CIA, FBI and NSA.
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/#78

I try again to copy the whole paragraph and the numbers missing
Well, in the days before the elections, there was constant interaction between the experts at CIA, FBI and NSA. We were monitoring and using our collection capabilities to understand what the Russians might have up their sleeve at the 11th hour.
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/

I copy another paragraph that has links and the number is missing:
This was the most aggressive and most direct and most assertive campaign that the Russians ever mounted in the history of our elections. And what characterized this were the variety and intensity of the techniques that they employed.
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/

Several times I’ve had to press the link a couple of times to get the green message that it has been copied – this may be a clue. (I’ve been careful in this test to only paste after I’ve gotten the green message.)

Now I’m copying a snippet of the original paragraph That does not have a link in it, and it’s correct every time:

elections, there was constant interaction bet
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/#78

nderstand what the Rus
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/#85

Now I’m going to another snippet that has one link, and it works as well:
The Russians will map the architecture and the environment of their targets
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/#147

Now going back to the original whole paragraph, and I get no number again:
Well, in the days before the elections, there was constant interaction between the experts at CIA, FBI and NSA. We were monitoring and using our collection capabilities to understand what the Russians might have up their sleeve at the 11th hour.
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/

**Comment by ethanbutler** [comment]
Closing because there's more info in #45.
