### ISSUE TITLE
Format no-media artifacts

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#52]
- [x] Warning appears just above the tabs – see picture.  This appears just in Interactive Pages.
- [x] Paragraph artifact in text "[[P]]" seems to have been inserted at the end of every line maybe to mark paragraphs, but is then left in the file and is formatted – see picture of how this text turned out. This happens both in Interactive Pages and Interviews

![image](https://user-images.githubusercontent.com/7329361/36745800-a1157218-1bbe-11e8-8ba1-e12006bae3c2.png)

**Comment by ethanbutler** [comment]
Look like #46 broke this.

**Comment by ethanbutler** [comment]
@KimPatch – this is marked as pending acceptance.

**Comment by KimPatch** [comment]
One bug: Now it puts an extra note paragraph, timecode and Period at the end of everything when the file does end with her.:

> WEBVTT
> 
> 00:00:01.000 --> 00:00:02.000
> Good morning, Dr. Carter!
> 
> NOTE paragraph
> 
> 00:00:02.000 --> 00:00:03.000
> "C.R.E.A.M." is not a song by Doug E. Fresh...
> 
> 00:00:03.000 --> 00:00:04.000
> Third sentence.
> 
> NOTE paragraph
> 
> 00:00:04.000 --> 00:00:05.000
> .
>

**Comment by ethanbutler** [comment]
@KimPatch – it looks like this would happen if there was a blank line at the end of the file. I pushed a change that cleans up beginning and ending whitespace before text is parsed, so this should be resolved.
