### ISSUE TITLE
Load More button for search is overactive

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#53]
**Current Behavior**: _When you hit the load more button after a search, and there are no more to load it loads duplicates._

**Desired Behavior**: _It shouldn't load duplicates and the load more button should disappear if all files are showing._

**Other details:** _I remember this happening on the interviews page at one point, but it was fixed. And it seems to work correctly currently on the interviews page._

**Comment by ethanbutler** [comment]
@KimPatch – I just pushed a fix for this that remove the load more button from the search results outright. In order to calculate the hit counts, our query has to return all the content anyway, so it didn't make sense to artificially paginate this content.

**Comment by KimPatch** [comment]
Great – I think loading them all makes more sense anyway – keeps things simpler. Thanks!
