### ISSUE TITLE
Handling NOTE in formatting (overlooked)

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#55]
**Current Behavior**: NOTE isn't handled in the text formatter any differently than regular text

**Desired Behavior**: NOTE followed by anything followed by a blank line should be treated spacing-wise like NOTE paragraph, and left with a blank line before and after it, and it shouldn't receive a timecode. _

**Other details:** It looks like this got lost in the shuffle – See Email 2/23/2018 9:15 AM

**Test**

NOTE Chapter This is a chapter title

Good morning, Dr. Carter!

"C.R.E.A.M." is not a song by Doug E. Fresh...

**Current  Results**
WEBVTT

NOTE paragraph

00:00:01.000 --> 00:00:02.000
NOTE Chapter This is a chapter titleGood morning, Dr. Carter!

NOTE paragraph

00:00:02.000 --> 00:00:03.000
"C.R.E.A.M." is not a song by Doug E. Fresh...

**Desired  Results**
WEBVTT

NOTE Chapter This is a chapter title

00:00:01.000 --> 00:00:02.000
Good morning, Dr. Carter!

NOTE paragraph

00:00:02.000 --> 00:00:03.000
"C.R.E.A.M." is not a song by Doug E. Fresh...

**Comment by ethanbutler** [comment]
I pushed a fix for this – the problem was that there was an extra line break when NOTES were hashed in the transcript that was causing the hashes not to get picked back up by the regex.

**Comment by KimPatch** [comment]
looks great!
