### ISSUE TITLE
Cursor behavior for search in phone and tablet view

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#58]
**Current Behavior**: _When you type text in the search box in the Phone and also at times in the tablet view, the cursor doesn't stay in the search box.  ._

**Desired Behavior**: The cursor should appear just in the text box._

**Other details:**: Everything works – the keyboard comes up and when you type it goes into the search box, but there’s a blinking cursor artifact advancing several lines below the search box. I think what's happening is the view is changing and the cursor is not aware of it. This happens when you scroll, and it happens all the time in Phone small view because when you click search, the view automatically changes because the keyboard moves the video up a bit.

![cursor artifact mar 02 2 31 40 pm](https://user-images.githubusercontent.com/7329361/36918037-8a0058b2-1e26-11e8-9f05-cc1d1f0d3b32.png)

**Comment by ethanbutler** [comment]
@KimPatch – this is a rendering bug in Webkit, see [https://bugs.webkit.org/show_bug.cgi?id=176896](this issue). This will be resolved in a future iOS update. I'll leave this issue open so we have a record of it.

**Comment by KimPatch** [comment]
understood – thanks for the explanation

**Comment by KimPatch** [comment]
Confirming that this has been resolved and now works correctly
