### ISSUE TITLE
Allow linking to a particular Timeline segment 

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#60]
How difficult would it be to make the Timeline headings links, so when you click a heading the direct URL would show up in the address bar (the same way it works for issues in github).

**Comment by ethanbutler** [comment]
This is trivial – I went ahead and implemented.

**Comment by KimPatch** [comment]
When I click a timeline entry it puts a number in the address bar – that's great. But it also takes me up one level to the timelines page – as if I also clicked the back button. I'm expecting The view to remain the same – the only thing that should change is the number be added to the address bar.

**Comment by ethanbutler** [comment]
@KimPatch – which browser are you in? This is working for me in OSX Firefox and Chrome.

**Comment by KimPatch** [comment]
I should have tested more thoroughly – it was Windows/Firefox. I reloaded with no add-ons and it's working as expected.  Windows/Chrome is good as well. So it's an add-on causing a problem.
