### ISSUE TITLE
Numbering pattern is incorrect above single numbers

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#65]
**Current Behavior**: _Numbering pattern uses two numbers per sentence passed double-digits._

**Desired Behavior**: _Numbering pattern should always be one number per sentence._

**Other details:** 

**Correct single number pattern**
00:00:07.000 --> 00:00:08.000
Text.

00:00:08.000 --> 00:00:09.000
Text.

**Incorrect double number pattern**
00:00:10.000 --> 00:00:11.000
Text.

00:00:12.000 --> 00:00:13.000
Text.

**Comment by ethanbutler** [comment]
@KimPatch – can you explain this differently or link to a specific example? I'm not following what's not working here.

**Comment by KimPatch** [comment]
Sorry – I see how that was completely unclear. 

When you click the Format No-Media button the numbering is fine up to double digits, with each line starting on a successive number. Once the numbering hits double digits each successive line starts on every other number. I flipped these above, which made it totally unclear. I just edited it to be correct. It should make more sense now.

**Comment by ethanbutler** [comment]
@KimPatch – Is this on the staging or production site? I'm not experiencing this – I just texted with `1. 2. 3. 4. ` etc, and everything matches up correctly.

**Comment by KimPatch** [comment]
This is good – everything matches up correctly on all three sites. The only thing I can think of is I could've tested originally before the demo site was updated.
