### ISSUE TITLE
Blog Features

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#67]
- [x] Widget support
- [x] Pagination
- [x] Category/tag archives

**Comment by KimPatch** [comment]
Widgets should be available for Posts, not just the blog homepage (the blog homepages going to be changed to mimic the site homepage anyway).

**Comment by ethanbutler** [comment]
@KimPatch – Widgets show up on individual posts, as well.

**Comment by KimPatch** [comment]
I'm not seeing this…

Under Appearance/Widgets I only see a box for Blog, and that works for the page named Dialog, which Posts flow into (this is the page that's slated to be redesigned to look like the homepage with the boxes). I added the categories widget to test this – I left that widget on for the moment. But there's no Posts category to add widgets to. I tried going through Live Preview to a post page that I just made and widgets weren't available. 
![image](https://user-images.githubusercontent.com/7329361/37365482-06569a2e-26d4-11e8-8164-540965d2137c.png)

What am I missing?

Also, can you add an author's widget (list of authors names plus number of posts, the viewer can click an author to get a page with just posts from that author).

**Comment by ethanbutler** [comment]
@KimPatch – You can add widgets through Appearance > Widgets. The WordPress customizer requires additional configuration in order to display the live previews – I didn't think this was worth the effort.

Can you open a separate issue for the authors widgets? [https://wordpress.org/plugins/authors/](This plugin) should be able to handle it, but I'll need to make sure there's actually an authors template.

**Comment by KimPatch** [comment]
I can add widgets only to the blog homepage through Appearance > Widgets. I can also do this through the customizer. This is the only that I can see that's available to add widgets to:
![image](https://user-images.githubusercontent.com/7329361/37540242-a07c5a58-292c-11e8-97a9-4ff3d4723f46.png)

**Comment by ethanbutler** [comment]
@KimPatch – this is on staging.

PR: #85

**Comment by KimPatch** [comment]
Thanks – this looks good. But there's one more related detail. Categories and tags don't show up at the end of a blog on the post pages – they should.
