### ISSUE TITLE
Interactive pages supporting content does not show up

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#69]
**Current Behavior**: _Supporting content doesn't show up on interactive pages._

**Desired Behavior**: _Supporting content should show up to the left of the text just like on Interviews._

**Other details:** I'm going through the Supporting Content tab to test this. I can select a timestamp, but when I update and go back there is no timestamp – I think this is the problem._

**Comment by KimPatch** [comment]
This is still not working. Take a look at 
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2285&action=edit

Test:
Put this in the Supp. Content .vtt tab:

> WEBVTT
> 
> 00:00:01.000 --> 00:00:02.000
> TITLE Test title
> DESCRIPTION Test description
> 
> 00:00:02.000 --> 00:00:03.000
> TITLE Test title
> DESCRIPTION Test description
> LINK http://livinghistory.sanford.duke.edu/interviews/abdus-salam/#5267

Check the box and update. 
The Supp. Content tab does not update, and the content does not show up on the page.

The time codes do show up in the Supp. Content tab. When I add supporting content through this tab it does show up on the page, but it also doesn't update the Supp. Content .vtt.

So I think now it's just that the two tabs aren't talking to each other.

**Comment by ethanbutler** [comment]
@KimPatch – looking through the source code, it looks like the issue is that you have LINK as an identifier. The identifiers that this parser recognizes are `URL` and `INTERNAL_URL`. If there's been some miscommunication with transcript providers and any of these labels need to be reworked, let me know.

**Comment by KimPatch** [comment]
My mistake – thanks. This looks good
