### ISSUE TITLE
Interactive pages don't have menu options

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#70]
**Current Behavior**: _Interactive pages don't have the back end control to add a menu._

**Desired Behavior**: _Interactive pages to have the back end control to add a menu._

**Other details:** For instance, the http://rlh.demo.sqnts.xyz/interactives/the-insite-system/ page needs to have the same menu as the other pages under Our Research

**Comment by ethanbutler** [comment]
@KimPatch – I pushed a change that adds an "Interactive" menu location to the site and adds a checkbox to interactives to toggle the menu visibility. Let me know if you have questions from here.

**Comment by KimPatch** [comment]
@ethanbutler I added an interactive menu and took a look. It looks like there are still a couple of issues. I'm looking at this in "The InSite System" interactive.
- [ ] The text doesn't move over properly
![image](https://user-images.githubusercontent.com/7329361/39678760-68183e50-5160-11e8-800b-0a59e71480eb.png)
There's not the usual bar above the Menu, and on the pages on the site, the bar now has space below it.
![image](https://user-images.githubusercontent.com/7329361/39679133-01dc7244-5167-11e8-8822-bd6cae506d36.png)
Here's how it looks on the regular Duke site  – without space
![image](https://user-images.githubusercontent.com/7329361/39679140-1c7fbee4-5167-11e8-8129-4b1b27494755.png)

A couple more things to discuss
- [ ] supporting content doesn't show up.  "The Insight System" Interactive has supporting content. The About interactive does not.
I was wondering if this is going to be an issue space-wise. I was going to suggest that if it is that when there's a menu on the Interactive pages the supporting content indicators be shortened like they are when the screen size gets small. Thoughts?
- [ ] Ideally, I'd like to add an existing menu to page. For instance, the InSite system page will take the Research menu and the Interactive About page will take the Standard menu. It would be better if we could just point to an existing menu. Is this possible and practical? (if we can't, maybe we could have a choice of interactive menu 1 and interactive menu 2, but this is much messier than if we can just point to an existing menu)

**Comment by ethanbutler** [comment]
@KimPatch - some notes here:

1. I pushed a fix to make sure the menu wraps properly.
2. There's no bar intentionally because the bar is the same color blue as the header, which I thought looked a little strange. I pushed a fix for the bar positioning on the other pages.
3. The supporting content on that interactive was incorrectly formatted – you need a `URL` field in order for an external link to "register." If you want a plain text node, you would want to supply a `CONTENT` field. I added a sample item for you so you can see how the spacing would look. (It looks like there's a bug with the y-axis placement, which I would imagine is because of the HTML in the transcript file).
4. This is certainly possible. I'll have time later this week to implement.

**Comment by KimPatch** [comment]
@ethanbutler 
1. Thanks – looks good.
2. Ok. Thanks.
3. Sorry – going too fast. I should have remembered that it's content not description.
Now that I see this properly, I'm thinking that the left margin of the interactive pages should match the right margin  if possible. Right now it's wider than the right margin and I think that's because it's the same as interview pages which are leaving more room for the video, but there isn't any video on these, and the text column really get small if you have both a menu and supporting content. **Question:** Is this relatively easy to do without messing up the interview pages? 

![image](https://user-images.githubusercontent.com/7329361/39773408-07784a7e-52c6-11e8-82d2-06e20f8d1e44.png)

4.  Great

**Comment by ethanbutler** [comment]
@KimPatch I just pushed a change that adds a dropdown to interactives that will let you select a menu.

The issue with the column width is that the site's layout is based around a percentage-based grid. Because the menu is left-aligned text, there's a variable amount of space between the edge of the text and the edge of the menu itself. I spent some time today exploring possibilities, and these are the two options:

1. Do a refactor of the site's layout that uses flexbox instead of percentages. This would be between 3-4 hours of work, as the timelines and interviews would need to be refactored as well.
2. If you let me know the name of the menu of the longest menu item, I can hard-code a width on the menu that would make the spacing equal. If you change the menu, this might need to be updated then as well.

**Comment by KimPatch** [comment]
@ethanbutler 
Great - thanks!
Thanks for the explanation. 
Question - if we hard code a width in the menu would that be for all pages or just for interactives? 
If it’s just the interactives the quick fix of hard coding would be best — a 30 character size would be ideal. We can shorten page titles on menus that appear with interactives if need be to keep within that. If that’s too long we can make 25 work. (Long term it would be good to refactor, but that’s low priority.)

**Comment by ethanbutler** [comment]
@KimPatch – that would be just for interactives, although for consistency's sake you might also want to apply a similar width on the other pages. If this sounds good, I can implement this week. Thanks!

**Comment by KimPatch** [comment]
@ethanbutler Great. If you can change it to 30 just on the the staging site so that would be great. I can then take a look and see if 30 gets us enough room and if it doesn't we can go a bit lower.
I think you're right, we should apply a similar width on the other pages – there are only a few of them and every menu item on them comes in under 30 now.

**Comment by ethanbutler** [comment]
@KimPatch – I just pushed a change to staging that sets this equal to roughly 25 characters. Attached are some screenshots for reference: one set to 30 characters, one set to 25, and one set to the longest menu item currently on the site). In my opinion, 25 was the optimal length – 30 shortened the transcript a little too much, and 25 gives a little bit of breathing room for the outdent on chapter headings. All of the screenshots are at 1200px. (If there are menu items that don't fit into this width, they'll just wrap to two lines.)

If 25 looks the best to you as well, can you mark this issue as accepted? Thanks!

![screen shot 2018-05-17 at 2 08 06 pm](https://user-images.githubusercontent.com/3719099/40196005-3557eefe-59dd-11e8-9e9d-24c71fa85199.png)
![screen shot 2018-05-17 at 2 07 08 pm](https://user-images.githubusercontent.com/3719099/40196006-356ce854-59dd-11e8-922a-c5c5fe7b010e.png)
![screen shot 2018-05-17 at 2 04 43 pm](https://user-images.githubusercontent.com/3719099/40196007-357bc626-59dd-11e8-9168-3393d397218d.png)

**Comment by KimPatch** [comment]
@ethanbutler 
This doesn't look like it makes the left and right margin spacing equal. 
![image](https://user-images.githubusercontent.com/7329361/40198810-7d307bd0-59e5-11e8-8afa-80b4f7729311.png)

The goal is to keep the column of text wider even when there's supporting content. It looks like the column is the same width whether it's 25 or 30. There's still quite a bit of extra space on the left, and it gets even wider on the left when there's supporting content, which is just when we need that space for the middle text. Is there any way to make the margins on the left and right equal, or much closer, especially when there is supporting content?

**Comment by KimPatch** [comment]
@ethanbutler – heads up I just updated the above comment to correct left/right – I guess I was picturing stage left…

**Comment by ethanbutler** [comment]
@KimPatch – apologies, I understood your message to refer to the distance between the transcript and the menu/supporting content (the second yellow area you marked). I'll re-implement.

**Comment by KimPatch** [comment]
@ethanbutler – it's both. It helped to cut down on the space between but using the extra space on the right would help even more.

**Comment by KimPatch** [comment]
@ethanbutler 
Thanks.  That's the right adjustment – it looks much better now. If it's quick to adjust a bit further…

1. It would be better if the end of the supporting content indicators lined up with the bar up at the top on the right. It still doesn't quite line up. 
![image](https://user-images.githubusercontent.com/7329361/40271675-443a25e4-5b6e-11e8-9d41-da020adcd17e.png)

2. And then when there isn't a menu there's a good amount of extra space on the right 
![image](https://user-images.githubusercontent.com/7329361/40271772-0caa1952-5b70-11e8-9e28-d75ebab627cd.png)

I think a good way to sum this up is the interactive pages are different from the interviews because the interviews need to have more margin on the right because the videos are going to take up that space, but since the interactive pages have no videos this margin should be different –  and lined up with the bar the top.

3. Also, there's one more bug here – the menu is showing up as "undefined" – see first picture above – I tried both the blog and standard menus, switched menus, updated, it still shows up undefined

And thanks for your patience on this one.

**Comment by ethanbutler** [comment]
@KimPatch – I fixed the above issues by adjusting some spacing. The "undefined" menu was due to an issue with how some of the menus were named, so I refactored this to work with existing content. If you've already set the "show menu" option on content, you _might_ need to reset this, as the field values are now different.

**Comment by KimPatch** [comment]
@ethanbutler 
Great! Menus are good. 
Spacing is good enough if this is tricky. But if it's possible to be more precise, we should be – it looks like they're still slightly off. 
Interactive with the menu is still a bit short:
![image](https://user-images.githubusercontent.com/7329361/40358614-d4769842-5d8d-11e8-8d56-d9e2624c97c3.png)
Interactive without the menu is even closer, but just a bit over.
Again, if this is as precise as it can be, it's good. But if it's a quick fix to adjust it would be better if they line up.
Thanks very much.

**Comment by KimPatch** [comment]
@ethanbutler 
It looks like the margins are now narrower on the interview pages on the production site. I suspect that's related to this change, so I'm putting this here rather than opening a bug. The interview pages margins  were already set and they need to be the way they were. They are different from interactive pages because they have videos and don't have sidebars. The margins changes should only affect the interactive pages, which don't have videos, and can have sidebars. I'm hoping you can remedy this right away.

**Comment by KimPatch** [comment]
@ethanbutler heads up – I made some edits to the above comment, including adding pictures

**Comment by KimPatch** [comment]
@ethanbutler heads up – I'm closing this again. I think I'm looking at slides from longer ago than I thought and the change isn't related to this. So it's probably best not to mess with this now.
