### ISSUE TITLE
New blog functionality

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#73]
- [x] Blog entry text box on the main homepage
- [x] Blogs on main search
- [x] Add blogs-only search to blog homepage and post-pages

**Comment by ethanbutler** [comment]
Notes: the blog entry text box will need an image and copy.

**Comment by KimPatch** [comment]
Blog entry text box looks good. Understood that we need an icon and bucket image.

Blog search should be as similar to the interview search as possible – as you type the term in, hits should be highlighted. And then when blogs are included in the main search, they should also have hits, just like the interview search.

**Comment by ethanbutler** [comment]
@KimPatch – I've added an icon as well as the fields you mentioned. I went ahead and uploaded a public domain stock image that I think looks nice. 

I won't have time today to get to the specially formatted search results, but I'll open up a separate issue for it. Thanks!

**Comment by KimPatch** [comment]
Nice. Thanks!

**Comment by KimPatch** [comment]
A couple of issues:
I put a blog entry on the staging site – looks good except 
- I was picturing that the content on the blog bucket on the front page would be the first number of words from the blog
- There's no need for categories/tags to appear in the box – just the beginning of the blog, and then the reader can click to get more (a related FYI when I changed the blog category it didn't change on the front page – we don't want the categories anyway, just saying in case it might be useful to know). 
- The "View the blog" link doesn't respond – both on the front page and also from the author and category pages does not respond. (the author link and the category links do respond – just not the view the blog link)

**Comment by ethanbutler** [comment]
@KimPatch – just want to make sure that the fixes in #72 wrap this up as well.
