### ISSUE TITLE
Enable Submenus

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#75]
**Current Behavior**: _When I moved a menu item to be a submenu in Appearance/Menus it broke the menu bar – the menu bar instead changed to a vertical menu bar on the right.._

**Desired Behavior**: _I expect the menu to remain horizontal and the submenu item to appear in a drop down under the menu._

A little more background:
Take a look at the primary menu: http://rlh.demo.sqnts.xyz/wp-admin/nav-menus.php
I left it configured with submenus. I guess the other way to say this is if we configure the primary menu with submenus the primary menu should keep acting like the primary menu – across the top of the site. We need to be able to adjust and test this to get it the way we want for the current changes. I also want to make sure content creators can add a menu item in the future.

**Comment by ethanbutler** [comment]
@KimPatch – this is on staging.

PR: #85

**Comment by KimPatch** [comment]
Thanks – looks good!
