### ISSUE TITLE
Supporting content alignment 

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#77]
**Current Behavior**: _When a supporting content dialog box is opened, all the supporting content below that box moves to wrong positions._

**Desired Behavior**: _Supporting content  dialog boxes that would be covered by the box that is open should move down immediately below the open supporting content dialog box, but the position of supporting content dialog boxes further down should not move out of place._

**Comment by KimPatch** [comment]
I'm looking at this with the civil rights timeline, which has a lot of supporting content:
http://rlh.demo.sqnts.xyz/timelines/civil-rights-and-voting-rights-in-north-carolina/

I'm expecting that when I open a supporting content dialogbox the items below it will move down just below the dialog box, and that may displace the next couple of items. But what happens is everything down the page is displaced. I see that after the initial opening some items jump up, and I understand if a few of the next items are displaced, but there is space that's not being used and everything down the line is displaced.

Here's an example – near the bottom of the timeline, with Gary Bartlett closed – highlighted.  And further down Shelby County v Holder points to the same section.
![image](https://user-images.githubusercontent.com/7329361/37559205-1e72216a-29f8-11e8-916d-52895fac2dfa.png)

But when I open Gary Bartlett Shelby County v Holder is pointing to the wrong section even though there is enough space for it to be pointing to the correct section.
![image](https://user-images.githubusercontent.com/7329361/37559221-451ee082-29f8-11e8-9bef-5944bfa9c8b2.png)

Is this something that's possible to fix?

**Comment by ethanbutler** [comment]
@KimPatch – the fix that I pushed for this was to recalculate the position for every item after any is expanded. I just pushed a fix that does this on contraction, too – that was an oversight on my part.

**Comment by KimPatch** [comment]
Looks good – thanks!
