### ISSUE TITLE
Transcript no media button should ignore period immediately followed by letters

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#78]
**Current Behavior**: _Transcript no media button splits URL's._

**Desired Behavior**: Transcript No Media Button shouldn't split URLs. 

**Other details:** 
I think the easiest way to do this is to make sure the transcriptional media button ignores periods immediately followed by letters.  

There's an example on the staging site:
2018-03-14 Blog Sample Interactive

**Here's how it splits the first bit incorrectly:**
00:00:01.000 --> 00:00:02.000
By Alena SadiAbdus Salam’s gravestone used to say, “First Muslim Nobel laureate” but, <a href="https://www.

00:00:02.000 --> 00:00:03.000
theguardian.

00:00:03.000 --> 00:00:04.000
com/science/2012/jul/08/higgs-boson-pakistan-scientist">according to Hoodbhoy</a>, a local magistrate ordered the word “Muslim” to be removed.

**Here's how it should be** :
00:00:01.000 --> 00:00:02.000
By Alena SadiAbdus Salam’s gravestone used to say, “First Muslim Nobel laureate” but, <a href="https://www.theguardian.com/science/2012/jul/08/higgs-boson-pakistan-scientist">according to Hoodbhoy</a>, a local magistrate ordered the word “Muslim” to be removed.

**Comment by KimPatch** [comment]
There's now a problem with tags. Maybe the easiest way to fix this is to always count  ".<" as a sentence.

(The other way would be to Fix the the web address problem just by ignoring multiple letters after a period rather than all characters.)

**Comment by ethanbutler** [comment]
@KimPatch – this looks good on my end of things. Maybe there was a caching issue you were running into? Would you mind checking again?

**Comment by KimPatch** [comment]
Test:
Take text from Post 2018-03-14 Blog Sample http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2281&action=edit
Paste it in an Interactive page and hit the button
Heres the result from just now: 
2018-03-17 format no media test 
HTML: 
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2359&action=edit
You can see the mistakes a little better on the page:
http://rlh.demo.sqnts.xyz/interactives/2018-03-17-format-no-media-test/
Two issues: 
It's a sentence and should be separated if there is a blank line after the period. There's an example on the Segment 1:
By Alena Sadi.Abdus Salam’s…
And then there issues with tags – there's one in Segment 2:
theory</a>.<blockquote><strong>ABDUS SALAM
And here's one more with a question long mark in segment 16
population?<strong>ABDUS SALAM:

**Comment by ethanbutler** [comment]
@KimPatch – This is a different issue than handling URLs. As we've discussed, the parser does not and cannot parse HTML. HTML is not a regular language. It's not possible to de-assemble and reassemble sentence while maintaining a nested HTML structure. I'm closing this and continuing the conversation in #66, which has more information.

**Comment by KimPatch** [comment]
This is separate from # 66, and I think this is almost there. I think we need three more pieces of logic:
- Treat a period followed by a blank line as a sentence and break it after the period (this addresses the first error).
Treat .< as a sentence and break it after the period (this addresses the second error)
Treat question marks and exclamation marks the same as periods (this addresses the third error)
Thanks for your patience with this – this is an important one.

**Comment by ethanbutler** [comment]
@KimPatch – I've pushed a change to staging that takes care of the first issue. I incorporated a change that makes it so that HTML is removed before parsing and reinserted at the same place in the formatted transcript. This will always require some additional work on the part of the content editor to make sure that tags are inserted back at the right place, but I don't think it's worth spending any more development effort on this issue because of our decision to move towards markdown-style syntax.

**Comment by KimPatch** [comment]
@ethanbutler This made it worse – now URLs are broken up. 

I'd like to go back to what we had before – we were almost there, and it was usable. 

If we can't take care of the first error we can get around that – we can deal with that differently on the content creator side.

**Question:** can you treat question marks and exclamation marks as periods?   (This is the one that addresses the third error)
**Question:** Right now there is logic to break a sentence if there's a period followed by a space. Can you add similar logic so that period followed by an angle bracket is also the site of a sentence break, and keep the angle bracket with the following sentence (This is the one that addresses the second error)

**Comment by KimPatch** [comment]
Here's a little more information related to the above:
I did the test above and then hand corrected it. 
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2383&action=edit
http://rlh.demo.sqnts.xyz/?post_type=interactive&p=2383&preview=true

I also got some stray text before the URLs (highlighted).
![image](https://user-images.githubusercontent.com/7329361/37624239-d8ad5292-2b9d-11e8-84b9-993c82e12f92.png)

I also hand-corrected the one from the 17th. This was a bit easier to hand correct.
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2396&action=edit
http://rlh.demo.sqnts.xyz/?post_type=interactive&p=2396&preview=true

I'm thinking 
- if you start with the one from the 17th and can do the two things above (Treat ? and ! same as periods, and break a period followed immediately by an angle bracket after the period, this would do it.) 
- or if there's a way to start with one from latest version from the 18th and put the URLs together and remove the stray text [[HTML:]], that would work too.

There is one other small thing that would help with it's easy to do – if the first line starts with "By" treat it as a separate paragraph

Thanks for your patience on this. This is close and very much what the content creators need.

**Comment by ethanbutler** [comment]
@KimPatch – upon spending more time with this, I've pushed a change to the staging server that should address the bulk of your concerns. I tested this change against the article, and it returns the text in full. It does not, however, handle HTML tags 100% correctly. It seems to handle <a> tags fine, but gets tripped up on any kind of nested structure. As explained in #66, this is a problem that can't be solved. 

I think the best thing thing to do is add a message warning content creators that HTML will not be parsed correctly, so that they're not surprised if they end up with garbled output.

**Comment by KimPatch** [comment]
@ethanbutler – thanks for keeping with this. Being able to even semi-automate this is extremely useful.
I tested this with the article and that file handles links well now – thanks.

1. But then I tested with a simple test and saw that it eats the last line. It doesn't matter what the last line is – it just disappears. There was logic in there that made sure that the last line didn't disappear if it didn't have a period after it, is that misfiring somehow? (This is a big issue because it's destructive – content creators might not notice the last line is missing.) 

I added a few more lines to the test so it had all the elements we've been talking about, and found a couple more things:

2. It also looks like it's breaking up sentences that have colons in them – colons should be ignored. (When I put colon on the whitelist it was ignored, but then I got odd characters Before the NOTE line, so I reversed that)
Here's what it's doing:

![image](https://user-images.githubusercontent.com/7329361/37678394-4ee5832e-2c54-11e8-932b-813ffc6c4a09.png)

Here's what it should do:
> 00:00:02.000 --> 00:00:03.000
> This line tests to make sure colon: is not treated like a period.
(This one isn't a showstopper if it's not easy to fix.)

3. Also, a period followed by an angle bracket:

> .< 

is ignored rather than broken at the period.
![image](https://user-images.githubusercontent.com/7329361/37678924-d6b60822-2c55-11e8-8c6d-d1338f8e2e42.png)

3. Understood that it gets tripped up on nested structure, but we had this working originally. Before the fix to handle url's, it just ignored the tags and so was not destructive, and that worked. If we went back to that it would be better.  Because these lines are now eaten – the content creators can't see what was supposed to be there. 

Here's the full results: http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2445&action=edit

And here's What I pasted as the original text before I hit the Format No-media button:

NOTE Chapter This is a chapter title

"C.R.E.A.M." is not a song by Doug E. Fresh...

This line tests to make sure colon: is not treated like a period (tests  #2).

This line tests to make sure semicolon; not treated like a period.

This line tests to make sure question marks are treated like a period?

This line tests to make sure exclamation marks are treated like a period!

The next line tests linking, and makes sure strong and blockquote tags are ignored (tests linking and #3).

Salam was a theoretical physicist who won the Nobel Prize in Physics, along with Sheldon Glashow and Steven Weinberg, in 1979 for his contribution to the <a href="https://www.nobelprize.org/nobel_prizes/physics/laureates/1979/">electroweak theory</a>.
<blockquote><strong>ABDUS SALAM:</strong> Yeah, I invented that name and I tried to sell it to Weinberg. In ’78 conference in Tokyo, I said that electroweak is a good name, a simple name which will be easier. “No, let’s keep it electricity and magnetism unified with nuclear forces and so on.” He was not very partial to that but later on it simply caught on and the other names all died out.</blockquote>

The eight lines after this one should be ignored because they have  HTML tags – they shouldn't be eaten. This was a problem early on but was fixed and working just before the link fix (tests  #3).

This line tests to make sure<br>
Lines with HTML tags are left alone<br>

<ul>
<li>As idiot proof as possible 
<li>PC/Mac and Android/iPhone agnostic
<li>Used as much open source software as possible
<li>Didn’t preclude keeping existing habits
</ul>

This is the second to last line(tests  #1 – there should be a line after this one).

This is the last line.

**Comment by ethanbutler** [comment]
@KimPatch – Thanks for providing the text case. After spending some more time with this, I think I have a solution that allows for HTML tags to not be eaten in the final markup. To be clear, they're not necessarily in a meaningful place, but nothing is lost. I've pushed this change, along with fixes for the missing final sentence and colon handling, to staging.

[Here's](https://regex101.com/r/0jHf2O/2/) where I'm testing out my parsing – you can see how the pattern I'm using splits text. Right now, it's covering every single character in your demo case, meaning that nothing is being eaten.

**Comment by KimPatch** [comment]
@Ethan Butler This looks great! And thanks for the details. You're right, the HTML tags are a little out of place, but that's not a big deal because it's easy to know to look for, find and fix. This does the trick. Thanks for keeping at this one.

**Comment by KimPatch** [comment]
Note: this is also related to #43 #63 and #66
