### ISSUE TITLE
Authors view for blogs

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#79]
Add authors widget so readers can view blog posts by author 

Note from Ethan:  [https://wordpress.org/plugins/authors/] (This plugin) should be able to handle it, but I'll need to make sure there's actually an authors template.

**Comment by ethanbutler** [comment]
@KimPatch – I tested out this plugin, and it works out-of-the-box with nothing needed to be changed on my end. I went ahead and installed it on the staging and production sites. I'll let y'all set it up, since there are quite a few configuration options offered for how authors are displayed.

**Comment by KimPatch** [comment]
Thanks – looks good
