### ISSUE TITLE
Date picker for Timeline supporting content is empty

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#80]
**Current Behavior**: Click supporting content timeline date picker and there are no dates there._

**Desired Behavior**: Content creator should be able to pick a Timeline date to associate supporting content with._

**Other details:** Test:
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=679&action=edit – click supporting content Tab, click select drop down under date – there's nothing there. (I checked this on the live Duke site and this was also the case there.)

**Comment by ethanbutler** [comment]
@KimPatch – this is on staging.

PR #85

**Comment by KimPatch** [comment]
Thanks!
