### ISSUE TITLE
Option for hiding the 8 boxes on the homepage

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#92]
**Current Behavior**: Homepage contains featured element, then a row of three boxes, then a section with 8 boxes.

**Desired Behavior**: Option for the Content Reader to opt not to have the section with 8 elements appear.  I'm picturing a backend checkbox to toggle the section with the eight boxes on/off.

**Note:** The blog homepage is going to be modeled after the site homepage, but retaining the eight boxes #72. It would also be more flexible also give the content creator the choice to toggle this element on/off on both the site homepage and the blog homepage, assuming this is easy to do.

**Comment by KimPatch** [comment]
I see that the eight boxes are gone from the homepage, but I don't see an option on the backend where the content creator can toggle these on and off.

**Comment by ethanbutler** [comment]
@KimPatch – this has been added.

**Comment by KimPatch** [comment]
great – looks good!
