### ISSUE TITLE
Hit numbers are sometimes incorrect

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#93]
**Current Behavior**: Hit numbers are often incorrect when using the site or collections search

**Desired Behavior**: Hit numbers to match hits

**Details**: This is consistent across searches. If there are a lot of hits, there's an undercount.
Example: search for identity – Jay Delancey entry says 6 hits, but then when you expand it's much more than that. 
![image](https://user-images.githubusercontent.com/7329361/38153326-1a9f37ac-343a-11e8-834f-167803a53328.png)

**Comment by KimPatch** [comment]
I'm still getting some wrong hit numbers – search on Vietnam:
Timeline: says 1 hit,  but you can see three
![image](https://user-images.githubusercontent.com/7329361/38559608-79639fc0-3ca1-11e8-8e52-ec7b5d0c78b0.png)

Interview: ssays 8 hits, but you can count 10
![image](https://user-images.githubusercontent.com/7329361/38559509-37faeb6a-3ca1-11e8-97c1-cbcb9f224098.png)

**Comment by ethanbutler** [comment]
@KimPatch – I see the confusion. In the current implementation each line/timestamp of an interview is counted as a hit, not necessarily each occurrence of a search term. The reasoning behind this is that individual timestamps are already computed, so it's trivial to get the total number of them. I can make this change if you'd like, but this was a decision made with performance in mind.

**Comment by KimPatch** [comment]
@ethanbutler – Understood.  If it's not a big performance hit, it would be better to change this to an accurate count of the actual hits.  Otherwise it's just going to look wrong to users.

**Comment by KimPatch** [comment]
@ethanbutler  looks great – thanks!
