### ISSUE TITLE
Heading size on the optional blog sidebar

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#98]
**Current Behavior**: The headings on the optional blog sidebar are larger than the blog title.

**Desired Behavior**: The sidebar headings should be just a little bigger than the entries so they don't overshadow the blog title.

**Other details:** Is it practical to give the content creators control of this on the backend? That would be best, but if not, we should bring down the size of the bullets as well, or eliminate them completely.

**Comment by KimPatch** [comment]
@ethanbutler – while you are here –  in the email thread I mentioned that it would be  good to make the sidebar font and weight the same as the author heading at the bottom of the page – it looks like the sidebar font is smaller now, but they are the same – can you make them the same?

**Comment by ethanbutler** [comment]
Sure thing – just pushed this change!
